import catPic from "../../assets/animalEnumImages/cat.jpg";
import {AnimalEnum} from "../model/AnimalEnum.ts";

export const animalsEnumImages: Record<AnimalEnum, string> = {
    ANTEATER: anteaterPic,
    ARMADILLO: armadilloPic,
    BEAR: bearPic,
    BEAVER: beaverPic,
    BIRD: birdPic,
    CAT: catPic,
    CHAMELEON: chameleonPic,
    CHICKEN: chickenPic,
    COW: cowPic,
    CROCODILE: crocodilePic,
    DEER: deerPic,
    DOG: dogPic,
    DOLPHIN: dolphinPic,
    DUCK: duckPic,
    EAGLE: eaglePic,
    ELEPHANT: elephantPic,
    FISH: fishPic,
    FOX: foxPic,
    FROG: frogPic,
    GIRAFFE: giraffePic,
    HEDGEHOG: hedgehogPic,
    HIPPOPOTAMUS: hippopotamusPic,
    HORSE: horsePic,
    KANGAROO: kangarooPic,
    KOALA: koalaPic,
    LLAMA: llamaPic,
    LION: lionPic,
    MONKEY: monkeyPic,
    MOUSE: mousePic,
    OCTOPUS: octopusPic,
    OWL: owlPic,
    PARROT: parrotPic,
    PENGUIN: penguinPic,
    PIG: pigPic,
    RACCOON: raccoonPic,
    RABBIT: rabbitPic,
    SHEEP: sheepPic,
    SKUNK: skunkPic,
    SNAKE: snakePic,
    SQUIRREL: squirrelPic,
    TIGER: tigerPic,
    TURTLE: turtlePic,
    WHALE: whalePic,
    WOLF: wolfPic,
    ZEBRA: zebraPic,
}